modelFileUrl: "https://github.com/api-generation/personal-details/blob/main/personal-details.xml"
outputDirUrl: "https://github.com/api-generation/personal-details/tree/main/generated/"
modelConfig:
  packageNames:
    typesPackage: "Personal Details"
dependencies:
  "Core Types":
    modelFileUrl: "https://github.com/api-generation/core-types/blob/main/generated/mtt-models/core-types.json"
    version: "1.0.0"
loader:
  generatorUrl: "http://localhost:8005"  
  configFileUrl: "https://github.com/mghaigh/common-config/blob/main/config/loaders/ea-xmi/config.yaml"
generators:
#  MkDocs:
  - generatorUrl: "http://localhost:9020"  
    configFileUrl: "https://github.com/mghaigh/common-config/blob/main/config/generators/mkdoc/config.yaml"



